version: "3"
services:
  mysql8.0:
    image: olasz/mysql-spring:0.0.7
    container_name: mysql-7
    ports:
      - 3380:3306
    environment:
      - MYSQL_DATABASE=springboot
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root
      - TZ=UTC
    volumes:
      - ./mysql8.0/logs:/var/log/mysql:rw

